### ISSUE TITLE
Schema validation fails when building schema with composite primary key.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#14] opened 2017-11-05 02:10 UTC
Seems like a schema definition error which doesn't allow us to define composite primary key:
```
#/primaryKey: #: 0 subschemas matched instead of one
org.everit.json.schema.ValidationException
	at org.everit.json.schema.ValidationException.prepend(ValidationException.java:332)
	at org.everit.json.schema.ValidationException.prepend(ValidationException.java:314)
```
Once fixed be sure to re-include primary key in _schema_valid_fk_string.json_ fixture, should look like this:
https://github.com/frictionlessdata/tableschema-py/blob/master/data/schema_valid_full.json

**Comment by iSnow** [comment] 2020-01-09 21:19
The ticket doesn't really provide a lot of information what went wrong and what the underlying problem might be. I copied over the `schema_valid_full.json` and created a matching data set `employee_full.csv` for a test.

Test code is:

    @Test
    public void testIssue14() throws Exception {
        Schema schema = Schema.fromJson (new File(getTestDataDirectory()
                , "schema/employee_full_schema.json"), true);
        Assert.assertNotNull(schema);

        File f = new File("data/employee_full.csv");
        Table table = Table.fromSource(f, getTestDataDirectory(), schema, null);
        List<Object[]> data = table.read();
        Assert.assertEquals(3, data.size());
    }

Test passes.

I believe the underlying issue was the [Schema definition problem](https://github.com/frictionlessdata/specs/issues/645) that caused problems validating schemas. Since this is fixed now, the problem is gone as far as I (or the test code) can tell.

**Closed by iSnow** 2020-01-09 21:19 UTC
Labels: bug, contribute
